import { useEffect, useState } from 'react';
import { Pulse, ArrowsClockwise, Bell, ChatCircle, Gear, Lightning, MagnifyingGlass, PaperPlaneRight, Pause, Robot, SignOut, UsersThree, WarningCircle } from '@phosphor-icons/react';
import './styles.css';

type Message = { id: string; direction: 'inbound' | 'outbound'; content: string; time: string; status?: string };
const nav = [{ label: 'Inbox', icon: ChatCircle }, { label: 'Leads', icon: UsersThree }, { label: 'Follow-ups', icon: ArrowsClockwise }, { label: 'Agent', icon: Robot }, { label: 'Automations', icon: Lightning }, { label: 'Integrations', icon: Gear }, { label: 'Test Lab', icon: Pulse }, { label: 'Observability', icon: WarningCircle }, { label: 'Settings', icon: Gear }];
const messages: Message[] = [{ id: '1', direction: 'inbound', content: 'Oi, vi o trabalho de vocês e queria entender como funciona.', time: '09:41' }, { id: '2', direction: 'outbound', content: 'Oi, tudo bem? Posso te explicar em poucos minutos. Hoje vocês fazem esse acompanhamento manualmente?', time: '09:42', status: 'read' }, { id: '3', direction: 'inbound', content: 'Sim, principalmente o primeiro contato e os retornos.', time: '09:44' }];

export function App() {
  const [active, setActive] = useState('Inbox'); const [draft, setDraft] = useState(''); const [items, setItems] = useState(messages); const [processing, setProcessing] = useState(false); const [connected, setConnected] = useState(false);
  useEffect(() => { const base = (import.meta.env.VITE_API_URL || 'http://localhost:8080').replace(/^http/, 'ws').replace(/\/$/, ''); const ws = new WebSocket(`${base}/ws/v1`); ws.onopen = () => setConnected(true); ws.onclose = () => setConnected(false); ws.onerror = () => setConnected(false); return () => ws.close(); }, []);
  const send = () => { const content = draft.trim(); if (!content || processing) return; setItems((old) => [...old, { id: String(Date.now()), direction: 'outbound', content, time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }), status: 'sending' }]); setDraft(''); setProcessing(true); window.setTimeout(() => { setProcessing(false); setItems((old) => old.map((item) => item.status === 'sending' ? { ...item, status: 'sent' } : item)); }, 650); };
  return <div className="shell"><aside className="sidebar"><div className="brand"><b>H</b><span><strong>HERMES</strong><small>OPERATION CONSOLE</small></span></div><p className="workspace">WORKSPACE <em>PROSPECT</em></p><nav aria-label="Navegação principal">{nav.map(({ label, icon: Icon }) => <button className={active === label ? 'nav active' : 'nav'} key={label} onClick={() => setActive(label)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="side-bottom"><p><i className={connected ? 'dot live' : 'dot'} />{connected ? 'API conectada' : 'API offline'}</p><button className="nav"><SignOut size={19}/><span>Sair</span></button></div></aside><main><header><div><small>OPERAÇÃO / {active.toUpperCase()}</small><h1>{active}</h1></div><div className="actions"><span className="environment"><i className="dot live"/> PRODUÇÃO CONTROLADA</span><button className="icon" aria-label="Notificações"><Bell size={20}/></button><span className="avatar">JQ</span></div></header>{active === 'Inbox' ? <Inbox items={items} draft={draft} setDraft={setDraft} send={send} processing={processing}/> : <div className="empty-page"><WarningCircle size={32}/><small>FASE DE IMPLEMENTAÇÃO</small><h2>{active}</h2><p>Esta área está prevista na especificação, mas ainda depende do contrato de API correspondente.</p><code>Sem dados simulados · aguardando endpoint real</code></div>}</main></div>;
}
function Inbox({ items, draft, setDraft, send, processing }: { items: Message[]; draft: string; setDraft: (v: string) => void; send: () => void; processing: boolean }) { return <section className="inbox"><aside className="conversations"><div className="panel-title"><div><small>ATENDIMENTO</small><h2>Conversas <sup>12</sup></h2></div><button className="icon" aria-label="Atualizar conversas"><ArrowsClockwise size={19}/></button></div><label className="search"><MagnifyingGlass size={17}/><input placeholder="Buscar conversa" aria-label="Buscar conversa"/></label><button className="conversation selected"><span className="contact">MC</span><span><b>Marina Costa</b><small>Sim, principalmente o primeiro contato...</small></span><time>09:44</time><mark>2</mark></button><button className="conversation"><span className="contact muted">RA</span><span><b>Rafael Almeida</b><small>Vou verificar com o time e retorno.</small></span><time>Ontem</time></button></aside><div className="chat"><div className="chat-head"><span className="contact">MC</span><div><b>Marina Costa</b><small><i className="dot live"/> Lead em qualificação</small></div><button className="pause"><Pause size={16}/>Pausar agente</button></div><div className="stream" aria-live="polite">{items.map((item) => <div className={item.direction === 'outbound' ? 'message outbound' : 'message'} key={item.id}><div><span>{item.content}</span><small>{item.time} {item.direction === 'outbound' && <em>{item.status === 'sending' ? '·' : '✓✓'}</em>}</small></div></div>)}{processing && <p className="activity"><i className="pulse"/> Hermes analisando...</p>}</div><div className="composer"><textarea rows={1} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Escreva uma mensagem..." aria-label="Mensagem"/><footer><span><Robot size={16}/>Agente ativo</span><button className="send" disabled={!draft.trim() || processing} onClick={send} aria-label="Enviar mensagem"><PaperPlaneRight size={18} weight="fill"/></button></footer></div></div><aside className="inspector"><div className="panel-title"><small>LEAD</small></div><div className="profile"><span className="contact big">MC</span><h2>Marina Costa</h2><small>Empresa não informada</small></div><section><label>STATUS</label><p><i className="dot live"/>Em qualificação</p></section><section><label>PRÓXIMA AÇÃO</label><p className="next"><strong>Qualificar necessidade</strong><small>Aguardando resposta do lead</small></p></section><section><label>INTEGRAÇÕES</label><p><span>Trello</span><em>Conectado</em></p><p><span>Follow-up</span><small>Não agendado</small></p></section></aside></section>; }
